# Generated by Django 4.2.27 on 2026-01-23 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('education', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Description du profil pour analyse NLP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=100)),
                ('required_experience', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(help_text='Détails du poste pour matching TF-IDF')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField()),
                ('text_similarity_score', models.FloatField()),
                ('experience_score', models.FloatField()),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.candidate')),
                ('job_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.joboffer')),
            ],
            options={
                'ordering': ['-overall_score'],
            },
        ),
        migrations.AddField(
            model_name='joboffer',
            name='required_skills',
            field=models.ManyToManyField(related_name='job_offers', to='matching.skill'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='skills',
            field=models.ManyToManyField(related_name='candidates', to='matching.skill'),
        ),
    ]
